Create README.md
newyorkmyc/keys-typeahead pull request #4
Opened 2024-10-15 18:04 UTC by mrozanoff

### Description: ✍️
creating readme

2024-10-15 19:50 UTC, newyorkmyc requested changes
The code looks great. However, you didn't run `pnpm install` or `npm install` on your local instance.

If you had, you would have been prompted with an error to fix your commit message.

See [commitizen](https://commitizen-tools.github.io/commitizen/) for global implementation on your work machine and or [commitlint](https://commitlint.js.org/) for this project.

Please also make sure you reference the 🎟️ # by linking to it in the PR description under the Issue(s) heading. e.g.: `#4` 

Please see my comments, run `npm install` and please commit with the proper commit format.

2024-10-15 19:50 UTC, newyorkmyc commented on README.md
> +
This project also requires you to run a local server otherwise you'll run into `CORS` issues with it trying to access `file://`

2024-10-15 19:50 UTC, newyorkmyc commented on README.md
> +npm init -y
This will just create a `package.json` folder, which we already have. This cmd is ran when you want to start a new project. 

See my previous comment about the server. Lets add that `cmd` here. I was using [http-server](https://www.npmjs.com/package/http-server)

2024-10-15 19:50 UTC, newyorkmyc commented on README.md
> +  - HTML / CSS / JavaScript for frontend
lets remove `for frontend` part.

2024-10-15 19:50 UTC, newyorkmyc commented on README.md
> +## Authors
🫶 this. 

Lets add the [all-contributors bot](https://github.com/all-contributors/app) in a follow up PR to handle this.

2024-10-15 19:50 UTC, newyorkmyc commented on README.md
> +
We need to add this `LICENCE.md` file to the repo. I'll open another issue against it.

2024-10-15 21:58 UTC, newyorkmyc commented
@mrozanoff, make sure you run a few cmds before making changes to your local:

```bash
#make sure you are on your branch
git checkout mrozanoff-readme

#get the latest commits from the #7 PR that was merged into this branch
git pull

#install all the npm modules
npm install
```

2024-10-18 01:50 UTC, Elaniobro approved these changes
New commits look great. It does look like we may have undone husky precommits, but we can fix it afterwards in a clean PR.

2024-10-18 01:50 UTC, Elaniobro commented on README.md
> +
This was added in #10

2024-10-18 01:50 UTC, Elaniobro commented on .husky/commit-msg
> +echo ‘Test  commit-msg hook’
This appears to be removing husky

2024-10-18 01:50 UTC, Elaniobro commented on .husky/pre-commit
> +echo ‘Test  pre-commit hook’
This appears to be removing husky

2024-10-18 01:50 UTC, Elaniobro commented on .husky/prepare-commit-msg
> -. "$(dirname -- "$0")/_/husky.sh"
This appears to be removing husky

2024-10-18 01:51 UTC, newyorkmyc approved these changes
Looks good. Lets merge and delete the branch.

Lets follow up with a PR to clean up husky with using npm.

2024-10-18 01:56 UTC, merged